[package]
name = "rusty-i8080"
version = "0.1.0"
authors = ["Matthew McDade <Matthew.McDade13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rustyi8080"
path = "src/cpu.rs"

[dependencies]
